### PR TITLE
Slightly update readme file + add screenshots

### PR DESCRIPTION
**Pull request by chschtsch**

### CODE REVIEW

**Comment by theScrabi** [comment]
Hm :/ make the screenshots smaller and please add the icon again.

**Comment by theScrabi** [comment]
Also don't make screenshots of a version with layout problems xDDD.

**Comment by theScrabi** [comment]
Here take this as an example:
https://github.com/grote/Transportr

**Comment by chschtsch** [comment]
OK. The icon was kinda weird and small, so I decided to remove it for now. Also, it's better to put link to http://dasochan.nl/newpipe/ on top of GitHub page, where it belongs:

screen shot 2015-12-01 at 8 23 12 pm

Or also, we can make gh-pages for this site, what do you think?

Readme in Transportr is looking pretty, I like it.
Maybe we can make icon slightly bigger, like theirs. And yes, small screenshots look good too (useful when multiple pages).

However, layout is an issue. I tried to convert to CardView, but it's challenging for me. Have you worked on it yet? We can discuss it on Slack, because I can do it, if somebody will explain why it's not as simple as change xml tags names and adding design libraries.

**Comment by theScrabi** [comment]
I already fixed stuff (as you se i used 3 commits to do so not very good but well).

**Comment by chschtsch** [comment]
Ok, sorry, I have outdated info.

**Pull request merged**
