### PR TITLE
Design update & refactoring

### PR DESCRIPTION
**Pull request by chschtsch**
- new CardView for video list items
- slightly reworked layout
- move all dimensions to `dimens.xml`
- better responsiveness for different screen sizes and orientations
- new like/dislike button

### CODE REVIEW

**Comment by chschtsch** [comment]
What do you think? Shall we push?

**Comment by wb9688** [comment]
Very nice!
Op 14 dec. 2015 13:06 schreef "Greg" <notifications@github.com>:

**Comment by theScrabi** [comment]
nnnnice work man :) nice work

**Comment by chschtsch** [comment]
I took my time to redraw them, so we're cool. Also, they are in higher resolution than original.

**Comment by timofonic** [comment]
New release, please! :) 

On December 14, 2015 9:48:41 PM CET, Greg <notifications@github.com> wrote:
>I took my time to redraw them, so we're cool. Also, they are in higher
>resolution than original.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/theScrabi/NewPipe/pull/114#issuecomment-164555037

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor disculpa mi brevedad.

**Comment by chschtsch** [comment]
Yeah we can release now, I already set version to 0.6.2.

**Pull request merged**
