### PR TITLE
Intent filters and other fixes

### PR DESCRIPTION
**Pull request by eighthave**
This flushes out the Intent Filters to cleanly match all the youtube URL patterns I could find.  It also includes some minor fixes related to translations and changes the default download folder to use the Android "Movies" folder.  Lots more comments in each commit.

### CODE REVIEW

**Comment by theScrabi** [comment]
Please don't switch the default Download folder to "Movies", NewPipe also downloads audio files, witch would mess up the idea of a "Movie" folder. One of the thinks I want to do next is to write a prober downloading part for NewPipe, therefore such changes are rather redundant.

**Comment by eighthave** [comment]
How about making so video files go to Movies and audio files go to Music?  For me the central issue is to use the standard locations.

**Comment by eighthave** [comment]
The other option is to put everything into *Download*

**Comment by theScrabi** [comment]
I don't like download either. I think I'll be OK with your first suggestion.

**Comment by eighthave** [comment]
also, I think this helps with #101 and #84 but not using the *Share* menu

**Comment by theScrabi** [comment]
I'll test and merge your code in the next few days.

**Comment by eighthave** [comment]
I think it probably makes sense to change the wording in `DownloadDialog` to match, so instead of *video* and *audio*, have it be *Movie* and *Music*.  That then provides a nice hint as to where the files will be downloaded.

**Comment by medavox** [comment]
What about audio books? And how to videos?

**Comment by theScrabi** [comment]
As I said id like to completely redactor downloading in the next few weeks. So all changes you do now might be obsolete.

**Comment by theScrabi** [comment]
@eighthave I saw you forgot to mark your code with Copyright, and license. Id like to add gpl to your code.

**Comment by eighthave** [comment]
of course, GPL is great!  Thanks for the merge, Tor one coming up next :)

**Comment by medavox** [comment]
I just mean that labeling all audio as "music", and all video as "movies" isn't strictly accurate. No code needs writing to support audiobooks uploaded to YouTube. But labeling them as music may be misleading.

**Comment by eighthave** [comment]
Think about the UX here.  I think if someone is downloading an audio
book, chances are they are going to play it using a music app.  And that
music app should use the default location for sound files:
/sdcard/Music.  I think the names of the folders is less important than
the user experience associated with them.

This is not a new or unique idea.  For example, OSX, Windows, and
GNU/Linux all have some standard version of these folders:

* ~/Documents
* ~/Downloads
* ~/Music
* ~/Pictures

Are there any dedicated audio book player apps?  Do they use the Music
folder?  Something like Audible is a closed system as far as I
understand it, it only plays files from its Amazon-based system. So it
is not a good example.

This seems to be one, but I just found it, I know nothing about it:
https://play.google.com/store/apps/details?id=ak.alizandro.smartaudiobookplayer&hl=en

**Comment by chschtsch** [comment]
Look at iTunes' behavior.
I don't use iTunes anymore, but as far as I know, it keeps all the data in `/Music/iTunes/iTunes media/` folder, including audiobooks.
So, I think it's OK to just stick to movies and music folders. Think of them like movies is for any video files and music is for any audio.

**Comment by theScrabi** [comment]
Also think about the technical difficulties, how should the app know what is music, and what is podcast. But still my opinion on this is, that we should generally divide NP content from the "default" content, by storing it inside its own folder.

**Comment by theScrabi** [comment]
@eighthave who should be the copyright holder? Me or the guardien project?

**Comment by medavox** [comment]
Everyone replying to my last comment above is correct; I just wanted to make sure that this was a conscious decision, rather than an oversight.

**Comment by eighthave** [comment]
About the copyright, it doesn't matter to me.  I generally like lots of
copyright holders because it makes it harder to convince all of the
contributors to change to a non-free license.

**Pull request merged**
