### PR TITLE
Update video search list

### PR DESCRIPTION
**Pull request by darkon5**
I adapted the search list so it would look nicer. I can only test on my screen, but I think it's an improvement. On my screen I get to see one more video on list.

(I only changed video_item.xml and dimentxt.xml, the rest was automated by Android Studio)

Before
Before

After
After

PD: I'm kind of newbie in this Git and Android Studio stuff. I'll try to keep the weirdness to a minimun.

### CODE REVIEW

**Comment by theScrabi** [comment]
Hm ok I'll merge it later. I was also thinking about another change. I want to put the duration on top of the video like the original app does, and then put the creation date where the duration was.

**Comment by darkon5** [comment]
You mean something like this? (the duration needs proper positioning)

screenshot_2015-09-20-13-48-30

**Comment by theScrabi** [comment]
Hm i had put it in the bottom right corner and mad it transparent like the original. But thats ok to :)

**Comment by theScrabi** [comment]
Actually i like that :) lets try it out.

**Comment by darkon5** [comment]
Well, I was changing it to the bottom left of the thumbnail too xD 

screenshot_2015-09-20-14-50-07

Colors can be changed on durationback.xml
(Original white colors -> Stroke: #4fa5d5, BG: #ffffff)

PS: Sorry if I'm slowing you down in the development. I'm learning ASAP about Android dev.

**Comment by theScrabi** [comment]
You are speeding it up !!! Now i don't need to do it my self. Thanks.

**Pull request merged**
