### PR TITLE
Added rewind capability to notification control

### PR DESCRIPTION
**Pull request by jaytj95**
added a button to notification panes (regular & expanded) that allows the user to start the audio over (`seekTo(0)`)

### CODE REVIEW

**Comment by theScrabi** [comment]
Could you please check why the CI fails?

**Comment by jaytj95** [comment]
Not really sure. The best I can come up with is

`/home/travis/build/theScrabi/NewPipe/app/build/intermediates/res/merged/debug/values-es/values-es.xml:2: AAPT: Error parsing XML: prefix must not be bound to one of the reserved namespace names`

**Comment by Gracecr** [comment]
I just ran the tests for this commit with the latest changes to master, and everything passed. Gradle build went just fine as well. @jaytj95, would you close and reopen this PR so that CI retests? This rewind feature is quite useful.

**Comment by jaytj95** [comment]
All done! Thanks

**Comment by theScrabi** [comment]
All right now let me do my changes that I will merge.

**Pull request merged**
