### PR TITLE
Integrated download manager.

### PR DESCRIPTION
**Pull request by satiricon**
It still needs work and features but it's already working well. Needs more testing tho.

### CODE REVIEW

**Comment by theScrabi** [comment]
Ok when I get my self out of that project deadlock im currently stuck in right now, I'll take a look at it :)

**Comment by timofonic** [comment]
Any news?

**Comment by theScrabi** [comment]
Moment, found time today.

**Comment by timofonic** [comment]
@theScrabi 


Thanks a lot! NewPipe is alive again :D

**Comment by theScrabi** [comment]
amazed cat
Nice, works :)

**Comment by satiricon** [comment]
Great! I‘ll be doing some stuff for NewPipe this starting week.

**Pull request merged**
