### PR TITLE
fix build. remove wrong xliff namespaces from spanish translation.

### PR DESCRIPTION
**Pull request by adelolmo**
This pull request should get the build back to normal.

### CODE REVIEW

**Comment by theScrabi** [comment]
Thanks :)

**Comment by adelolmo** [comment]
About the test failing (YoutubeSearchEngineTest.testIfNoErrorOccur): to fix it you have to change the search term. If you use "cats" instead of "star wars" the test will pass.

**Comment by adelolmo** [comment]
I finally use the term "this is something boring" for the search in YoutubeSearchEngineTest.
The key is to avoid search which have any ads or channels. Plus the results must have more than 1000 views in the first result page (not 100% sure here).

**Comment by theScrabi** [comment]
Yea I already thought about lowering the minimum views, since that sometimes fails. I just want to test if the numbers are (at least a bit) correct.

May have to change that.

**Pull request merged**
