### PR TITLE
Adding the loading screen when user scroll through videoList. 

### PR DESCRIPTION
**Pull request by narutosanjiv**

### CODE REVIEW

**Comment by narutosanjiv** [comment]
ScreenShot showing functionality.
screenshot

**Comment by narutosanjiv** [comment]
@theScrabi  Build is failing without any specific reason. It failed with message "The command "./gradlew build connectedCheck" exited with 1."

**Comment by theScrabi** [comment]
build failes because travis cant handle the sdk we currently use, so it might not be your fault.

**Comment by narutosanjiv** [comment]
Does functionality look good?.

**Comment by theScrabi** [comment]
looks nice. I'll try and merge it the next few days :)

**Comment by theScrabi** [comment]
Nice improvement thanks :)

**Pull request merged**
