### PR TITLE
Duration now shown on top of the thumbnail.

### PR DESCRIPTION
**Pull request by darkon5**
TODO: Replace "Upload date here" with actual upload time, change colors to taste.

(I leave these to you as I think you will make better changes than I could)

### CODE REVIEW

**Comment by darkon5** [comment]
+ Spanish translation :)

**Comment by darkon5** [comment]
I made another version where the title is more thin and the upload date and author have different lines.
This is good for the videos with long author names, this way text won't glitch that often.

-> THIS IS NOT INCLUDED IN THIS PULL REQUEST <-

Should I add these changes too?

screenshot_2015-09-20-18-17-01

**Comment by theScrabi** [comment]
Ah we have a problem. Sometimes the user name is so long, that the layout crashes. For now i put the itemUploadDateView benath the username, but that doesn't look pretty good.
screenshot_2015-09-20-20-58-26

**Comment by darkon5** [comment]
In my smaller version it does not happen:

screenshot_2015-09-20-21-34-10

I'm going to make the final touches and send it for testing. It shouldn't crash with anything.

**Comment by theScrabi** [comment]
k thanks

**Pull request merged**
