### PR TITLE
Allow for large times stamps fixing #330

### PR DESCRIPTION
**Pull request by Gracecr**
@scde submitted #330, along with a couple proposed fixes.
This is the second proposed fix, which allows for arbitrarily large
timestamps. All credit to @scde for this.

### CODE REVIEW

**Comment by Gracecr** [comment]
Not sure why the build failed, but I don't believe it has to do with the changes made in this PR.

**Comment by theScrabi** [comment]
Hm did it work for you?

**Comment by Gracecr** [comment]
On my machine, all tests passed. Not sure why there is a difference in the Travis CI build. I could close and reopen this PR to have Travis retest, maybe it is something on YouTube's end.

**Comment by theScrabi** [comment]
Yes thats moslty the case.

**Comment by Gracecr** [comment]
Looks like that did the trick. Just something with YouTube.

**Pull request merged**
