### PR TITLE
UI improvements & better image loading

### PR DESCRIPTION
**Pull request by algoprog**
1. Removed the CardView style for better readability
2. View counts are now shown in all search results and in short format (ex. 127K, 23M)
3. Video description can be shown/hidden by clicking on the video title
4. Similar videos are now in the same activity with the video (no button)
5. Fixed issue #139
6. Parallax scrolling fixed in VideoItemDetailFragment layout
7. Removed all the code related to image loading and used Universal Image Loader
8. Unwanted activity reload on orientation change fixed
9. New screenshots

[](https://raw.githubusercontent.com/algoprog/NewPipe/master/screenshots/screenshot_1.png) [](https://raw.githubusercontent.com/algoprog/NewPipe/master/screenshots/screenshot_3.png) [](https://raw.githubusercontent.com/algoprog/NewPipe/master/screenshots/screenshot_4.png) [](https://raw.githubusercontent.com/algoprog/NewPipe/master/screenshots/screenshot_5.png)

I tested the app on Android 5.0.1 but it should work without any problems with older versions too. I am also working on search & view history. What do you think?

### CODE REVIEW

**Comment by wb9688** [comment]
Did you tested it on a tablet in landscape mode?
Op 4 feb. 2016 20:09 schreef "Chris Samarinas" <notifications@github.com>:

**Comment by algoprog** [comment]
I will test it now, but it should be ok.

**Comment by algoprog** [comment]
[](tablet.png)

**Comment by algoprog** [comment]
Two small changes could be to make the text white when an item is highlighted in the listfragment and change the alignment of NEXT VIDEO and SIMILAR VIDEOS to left. But that could be done later.

**Comment by theScrabi** [comment]
Nnnnice. I'll try to merge it in the next few days :)

**Comment by algoprog** [comment]
No, but the 3 new libraries I used (Universal Image Loader, Circular ImageView and Parallax ScrollView) are compatible with older versions. Also I didn't write any code that works only with latest APIs, so it should be fine. I will test it though to confirm this.

**Comment by theScrabi** [comment]
Ok. I'll also test once again it before merging it.
Also if you like, our player needs a new UI. Our current one is acting kind of weird, and doesn't look that nice either.

**Comment by theScrabi** [comment]
I don't know image loader, but is it possible to use a custom network backend? I'd like to be able to download the thumbnails using NetCipher, so we can download it via tor.

**Comment by algoprog** [comment]
Yes. You can set a custom downloader. See the configuration options: https://github.com/nostra13/Android-Universal-Image-Loader/wiki/Configuration

**Comment by algoprog** [comment]
Universal Image Loader is initialized in App. You can set the custom downloader or any other configuration options there.

**Comment by theScrabi** [comment]
Ok although it might not seam so, I have merged it.

**Comment by theScrabi** [comment]
Oh didn't see your last comment yet. Ok thats good :)

**Comment by theScrabi** [comment]
Question. VideoItemDetail activity is only working it portrait mode, not in landscape. Is that wanted? So or so please add landscape mode again, because at the moment the behaviour on tablets is a bit messy. I also encountered some other bugs and improvements, can you please come over to our [slack](http://invite.chschtsch.ml/) group, so we can maintain these problems.

**Comment by algoprog** [comment]
I was thinking of incorporating the video player in VideoItemDetail activity. It will be in fixed position and will switch to fullscreen mode when in landscape or when fullscreen button is clicked on the player, and back to normal when in portrait mode (like the official YouTube app). I believe that's the best option for both small and large screens. If you still want landscape mode back it's just a small change in AndroidManifest.xml.

**Comment by theScrabi** [comment]
That's more or less the behavior of the original youtube app. Well I don't know. I have different plans for NewPipe. So for now we should stick to the design of an extra activity for the video player.

**Pull request closed without merging**
