### PR TITLE
File picker for download preferences.

### PR DESCRIPTION
**Pull request by satiricon**
I still have to make the latest filepicker version work but meanwhile it's working pretty well with an older version.

### CODE REVIEW

**Comment by satiricon** [comment]
I don't know why the test would not pass. I tested on my machine and they passed flawlessly.

**Comment by theScrabi** [comment]
Yea it's just that view count thing. This never worked correctly. The rest is fine though.

... need to fix that test one day.

**Comment by theScrabi** [comment]
File picker does not seem to change download directory.

**Comment by theScrabi** [comment]
I noticed, if you call filePickerActivity, it will return immediately giving a Nullpointer as result.

**Comment by satiricon** [comment]
@theScrabi I'm checking this out.

**Pull request merged**
