### PR TITLE
Video Detail Layout Update

### PR DESCRIPTION
**Pull request by darkon5**
Yay, I made something! Here I have the latest version of my layout for NewPipe. Still a lot to work and learn, but I think it's getting into shape. Changes overall:

- New logo for the main screen (made by @halcyonest).
- New "NewPipe Red" color (#CD322E) :P
- Reworked Video Detail Layout:
  - Before: http://i.imgur.com/gtLeQpf.png
  - After:http://i.imgur.com/mMHvWft.png

It's still a work in progress, I'll keep working on it. Also, in my school we need to make a webpage using HTML and CSS, so I made this: http://dasochan.nl/newpipe/

If the project gets a homepage, I think this one could be a good start :)

That was it for today, g'night! ^.^

### CODE REVIEW

**Comment by theScrabi** [comment]
Sry I didn't notice this earlier. Sorry I broke your pull request. Great work. Cool website. Thanks man :)

**Comment by theScrabi** [comment]
Hm but could you put the thumbs up and down arrows somewhere else, it looks like they are grading the channel not the video.

**Comment by darkon5** [comment]
Sure thing, I'll try to fix it today.

**Comment by theScrabi** [comment]
Again, you may have to stash your changes and pull from the master, i cant merge your branch since we crashed into each other.
Sry.

**Comment by darkon5** [comment]
Oh, true. Gotta try to sync it manually then =)

**Comment by darkon5** [comment]
Okay, I know I shouldn't doing this, but I don't know anyone to ask: When I build the latest version of NewPipe on Android Studio, I get this error:

Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 1

Any idea why this is happening? I technically ported the layout to the new version, but I can't properly test it on my device.

g'evening! =)

**Comment by theScrabi** [comment]
Hm. I don't know. But you are using Windows. Maybe you should get rid of that first ;D

**Comment by theScrabi** [comment]
Madovax recently did changes on the jdk version in the .idea/gradle.xml file:
https://github.com/theScrabi/NewPipe/commit/a18353df5f3bd377c1d088cd1b611d71841e18fd
Maybe thats causing your trouble.

**Comment by theScrabi** [comment]
Ok i think than this is fixed.

**Comment by darkon5** [comment]
Thanks @chschtsch!

I still have issues with Android Studio, I might do a complete format on my machine.

**Pull request closed without merging**
