### PR TITLE
Update layout (initially suggested by @darkon5) + miscellaneous fixes

### PR DESCRIPTION
**Pull request by chschtsch**
In these commits I implemented some of the features suggested by @darkon5 in #56.

Firstly, I manually set English as default language for all http requests (hardcode), but then I saw new commits by @medavox and rolled it back for not messing up his own plans of implementing new functionality in #68.

### CODE REVIEW

**Comment by medavox** [comment]
Didn't realise you were working on this also, sorry!

**Comment by chschtsch** [comment]
No irony intended, you better knew what to do. (I noticed that my solution was just temporary hardcode)

**Comment by theScrabi** [comment]
Seems to me like we need a prober work flow for this repository. I'm to open up an issue about that.

**Comment by medavox** [comment]
I'm new to collaborative coding, so I'm all for this.

**Comment by theScrabi** [comment]
Well i'm to. Thats the problem.

**Pull request merged**
